/* Persistent Nika demo on learning pages. */
(()=> {
 if(document.querySelector("#guide-toggle"))return;
 document.body.insertAdjacentHTML("beforeend",`<button class="guide-orb" id="guide-toggle" aria-label="Abrir asistente virtual" aria-expanded="false"><img src="assets/virtual-guide.png" alt="Nika"><span>✦</span></button><aside class="virtual-guide" id="virtual-guide"><button class="guide-close" id="guide-close">×</button><img class="guide-avatar" src="assets/virtual-guide.png" alt=""><p class="eyebrow">TU GUÍA VIRTUAL</p><h3>Hola, soy <i>Nika.</i></h3><p>Estoy contigo durante todo el recorrido.</p><div class="guide-actions"><a href="test-nivel.html">Hacer mi test de nivel <span>→</span></a><a href="reservar.html">Reservar una clase <span>→</span></a><a href="plataforma.html">Jugar y practicar <span>→</span></a></div><div class="guide-tools"><button id="guide-speak">🔊 Escuchar a Nika</button><button id="guide-mic">🎙 Hablar con Nika</button></div><select class="guide-language" id="guide-language"><option value="es-MX">🎙 Hablar en español</option><option value="ru-RU">🎙 Говорить по-русски</option></select><form class="guide-chat" id="guide-chat"><input id="guide-input" placeholder="Escríbele a Nika..."><button>Enviar</button></form><p class="guide-message" id="guide-message">Escribe o habla conmigo.</p></aside>`);
 const toggle=document.querySelector("#guide-toggle"),panel=document.querySelector("#virtual-guide"),close=document.querySelector("#guide-close"),mic=document.querySelector("#guide-mic"),speakBtn=document.querySelector("#guide-speak"),message=document.querySelector("#guide-message"),input=document.querySelector("#guide-input"),chat=document.querySelector("#guide-chat"),language=document.querySelector("#guide-language");
 const say=(es,ru)=>{message.textContent=es;if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const vs=speechSynthesis.getVoices(),female=/female|femen|mujer|zira|paulina|dalia|helena|laura|sabina|monica|irina|elena|katya|milena/i,pick=l=>vs.find(v=>v.lang?.toLowerCase().startsWith(l)&&female.test(v.name))||vs.find(v=>v.lang?.toLowerCase().startsWith(l));[[es.replace(/\bMasha\b/gi,"la profesora"),pick("es")],[ru,pick("ru")]].forEach(([text,v])=>{if(v){const u=new SpeechSynthesisUtterance(text);u.voice=v;u.lang=v.lang;u.rate=.92;speechSynthesis.speak(u)}})};
 const respond=t=>{t=t.toLowerCase();if(/nivel|test|prueba|уров/.test(t))say("Puedo explicarte el test de nivel: tiene diez preguntas y llega hasta B2.","Я могу объяснить тест уровня: в нём десять вопросов, до уровня B2.");else if(/clase|reserv|horario|урок/.test(t))say("Las clases son individuales con Masha por Zoom, plataforma y pizarras digitales.","Индивидуальные уроки проходят с Машей в Zoom, с платформой и досками.");else if(/hola|привет/.test(t))say("¡Hola! Me alegra conocerte. Pregúntame por el test, clases o plataforma.","Привет! Рада познакомиться. Спроси меня про тест, уроки или платформу.");else say("Estoy en modo de demostración. Puedo orientarte sobre el test, clases, precios y plataforma.","Я в демо-режиме. Могу подсказать о тесте, уроках, ценах и платформе.")};
 const open=()=>{toggle.classList.add("launch");setTimeout(()=>{panel.classList.add("show");toggle.setAttribute("aria-expanded","true");toggle.classList.remove("launch");say("Hola, soy Nika. Estoy aquí contigo en esta página.","Привет, я Ника. Я рядом с тобой на этой странице.");},340)};
 toggle.onclick=()=>panel.classList.contains("show")?(panel.classList.remove("show"),toggle.setAttribute("aria-expanded","false")):open();close.onclick=()=>{panel.classList.remove("show");toggle.setAttribute("aria-expanded","false")};speakBtn.onclick=()=>say("Pregúntame sobre el test, las clases o la plataforma.","Спроси меня о тесте, уроках или платформе.");chat.onsubmit=e=>{e.preventDefault();if(input.value.trim()){respond(input.value);input.value=""}};
 mic.onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){message.textContent="Este navegador no reconoce el micrófono. Escríbeme abajo.";return}const r=new R();let got=false;r.lang=language.value;r.interimResults=false;r.onresult=e=>{got=true;respond(e.results[0][0].transcript)};r.onerror=e=>{message.textContent=e.error==="not-allowed"?"Permite el micrófono en el navegador y pulsa otra vez.":"No recibí una frase. Puedes intentarlo otra vez o escribirme."};r.onend=()=>{if(!got&&message.textContent.includes("Te escucho"))message.textContent="No recibí una frase. Prueba otra vez o escribe tu pregunta."};message.textContent="🎙 Te escucho… habla ahora.";try{r.start()}catch{message.textContent="Pulsa otra vez el micrófono para hablar."}};
})();