/* Persistent Nika widget for every learning page. */
(() => {
  if (document.querySelector("#guide-toggle")) return;
  const markup = `<button class="guide-orb" id="guide-toggle" aria-label="Abrir asistente virtual" aria-expanded="false"><img src="assets/virtual-guide.png" alt="Nika, asistente virtual"><span>✦</span></button><aside class="virtual-guide" id="virtual-guide" aria-label="Asistente virtual"><button class="guide-close" id="guide-close" aria-label="Cerrar">×</button><img class="guide-avatar" src="assets/virtual-guide.png" alt=""><p class="eyebrow">TU GUÍA VIRTUAL</p><h3>Hola, soy <i>Nika.</i></h3><p>Estoy contigo durante todo el recorrido. ¿Qué necesitas?</p><div class="guide-actions"><a href="test-nivel.html">Hacer mi test de nivel <span>→</span></a><a href="reservar.html">Reservar una clase <span>→</span></a><a href="plataforma.html">Jugar y practicar <span>→</span></a><a href="https://wa.me/524421562187?text=Hola%20Masha%2C%20tengo%20una%20pregunta%20sobre%20los%20cursos." target="_blank" rel="noopener">Hablar con Masha <span>↗</span></a></div><div class="guide-tools"><button id="guide-speak" type="button">🔊 Escuchar a Nika</button><button id="guide-mic" type="button">🎙 Hablar con Nika</button></div><p class="guide-message" id="guide-message">Dime: «nivel», «clase», «juego» o «WhatsApp».</p></aside>`;
  document.body.insertAdjacentHTML("beforeend", markup);
  const toggle=document.querySelector("#guide-toggle"),panel=document.querySelector("#virtual-guide"),close=document.querySelector("#guide-close"),speakButton=document.querySelector("#guide-speak"),mic=document.querySelector("#guide-mic"),message=document.querySelector("#guide-message");
  const setOpen=open=>{panel.classList.toggle("show",open);toggle.setAttribute("aria-expanded",String(open))};
  const speak=(text,voiceText=text)=>{message.textContent=text;if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();let spoken=false;const playRussian=()=>{if(spoken)return;const voice=window.speechSynthesis.getVoices().find(item=>item.lang&&item.lang.toLowerCase().startsWith("ru"));if(!voice)return;spoken=true;const u=new SpeechSynthesisUtterance(voiceText);u.lang=voice.lang;u.voice=voice;u.rate=.92;window.speechSynthesis.speak(u)};playRussian();if(!spoken){message.textContent="Nika hablará en ruso cuando haya una voz rusa disponible en este dispositivo.";window.speechSynthesis.addEventListener("voiceschanged",playRussian,{once:true});setTimeout(playRussian,900)}};
  const reply=spoken=>{const t=spoken.toLowerCase();if(/nivel|test|prueba/.test(t)){speak("Vamos al test de nivel. Te acompañaré durante las preguntas.","Переходим к тесту уровня. Я буду рядом во время вопросов.");setTimeout(()=>location.href="test-nivel.html",900)}else if(/clase|horario|reserv/.test(t)){speak("Abriré la reserva para que elijas tu horario.","Я открою запись, чтобы ты выбрала удобное время.");setTimeout(()=>location.href="reservar.html",900)}else if(/juego|material|practic|plataforma/.test(t)){speak("Vamos a practicar con la mini juego de ruso.","Давай потренируем русские слова в мини-игре.");setTimeout(()=>location.href="plataforma.html",900)}else if(/whatsapp|masha|pregunta|ayuda/.test(t)){speak("Te conecto con Masha por WhatsApp.","Я соединю тебя с Машей в WhatsApp.");setTimeout(()=>window.open("https://wa.me/524421562187?text=Hola%20Masha%2C%20tengo%20una%20pregunta%20sobre%20los%20cursos.","_blank","noopener"),900)}else speak("Todavía entiendo mejor estas palabras: nivel, clase, juego o WhatsApp.","Я лучше понимаю слова: уровень, урок, игра или WhatsApp.")};
  toggle.onclick=()=>setOpen(!panel.classList.contains("show"));close.onclick=()=>setOpen(false);
  speakButton.onclick=()=>speak("Hola, soy Nika. Puedo acompañarte con el test de nivel, una reserva, la plataforma o WhatsApp.","Привет, я Ника. Я помогу с тестом уровня, записью на урок, платформой или WhatsApp.");
  mic.onclick=()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){speak("Tu navegador no permite usar el micrófono aquí. Puedes usar mis botones.","Твой браузер не поддерживает микрофон. Используй мои кнопки.");return}const recognition=new Recognition();recognition.lang="es-MX";recognition.interimResults=false;recognition.maxAlternatives=1;speak("Te escucho.","Я слушаю.");recognition.onresult=e=>reply(e.results[0][0].transcript);recognition.onerror=()=>speak("No pude escucharte. Prueba otra vez.","Я не смогла тебя услышать. Попробуй ещё раз.");recognition.start()};
  setTimeout(()=>setOpen(true),650);
})();